language: java
jdk:
- oraclejdk8
deploy:
  provider: "elasticbeanstalk"
  access_key_id: "AKIAJ34CCCRBU65UOR3Q"
  secret_access_key:
    secure: "KA1QlRqw6YcQKmKBE8qEpMETM65jbNyzY0RWlXcXb9RKzIe3AYUOaqDaT/3z7nO3kAfPhh0lxTLdf8kDOkBoi5GTt7kIvFX6Fbu2kFTz5HeAHU9z2BZPQ5/aWA6j4ozCvX4B+3HC4yPC6Bwj7MB6VZsj7D+uQgH6I2fm98e4fO0HbjS43Y5SVlmSAh61B4Svf12Xss8U6NOm+lH2XDYoMrr2Y0THTrfSMmjvsVS5IPGZpdYP57u5rlsr3gtw7/Lw7JKsMsslS7uMpn66+nTZTehw3j6LVvCQVG/GP1iTx+3YzYmM1PYEKruBIf0ONEqwxGyR586j8LQksp2W2U7uWp1gNdnQOI67F3fhZOZSxZZ7UdU+vwMJOd51zsYChgCqdN4xHZZ1Dk6TnkAa67k0FT5DJrHYVAbDiS/B6To514l5O6zbamA6ena+S19DA06z+6WoFb8EqQq7Qr4kX59l0kmSzOq4pADKaLA79G7CJJ4eVZ3+t8qqCP6gTqQ3ERlvIpl2oNAJvyGEcHfQ8HAHcLAI9BB16H042fFCT7XfKkiV6yNgNH23pPT9BxvV87axxv3k+SaL2OGC/2U1qsYq9zuTKJEZqhbcMtyP4ap1KWbRVlBjcmn6KAG6OyUbxs4g754WTr/1tAMDQ7/E+Bzec0614BF6OqVZOk3E/8nbWlU="
  region: "eu-west-2"
  app: "mdd-050-api"
  env: "Mdd050Api-qlf"
  bucket_name: "elasticbeanstalk-eu-west-2-721501699470"
  on:
    branch: "correction"
